/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.ui;

import java.awt.*;
import main.app.GameContext;
import main.eventHandlers.KeyHandler;
import main.logic.GameUpdate;

/**
 *
 * @author PCC
 */
public class GamePanel extends javax.swing.JPanel {
    private GameContext gameContext;
    private KeyHandler keyH;
    int x =0, y =0;
    /** 
     * Creates new form GamePanel
     * @param gameContext
     */
    public GamePanel(GameContext gameContext) {
        this.gameContext = gameContext;
        this.keyH = gameContext.getKeyH();
        
//        initEvents();

        this.setFocusable(true);
        this.setDoubleBuffered(true);
        this.requestFocusInWindow(); // Request focus for key events
        
        gameContext.getKeyH().bindKeyActions(this);

        initComponents();
        
    }
    
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;

        draw(g2);

        g2.dispose();
        
    }
    
    
    private void draw(Graphics2D g2){
        g2.setColor(Color.WHITE);
        g2.fillRect(x, y, 50, 50);

    }
    
    public void gpUpdate(){
        if (keyH.isUpPressed()) y-=3;
        else if (keyH.isDownPressed()) y += 3;
        else if (keyH.isLeftPressed()) x -= 3;
        else if (keyH.isRightPressed()) x += 3;
         
//        x+=10;
//        y+=10;
        // Ensure x and y remain within bounds
        if (x < 0) x = 0;
        if (y < 0) y = 0;
        if (x + 50 > getWidth()) x = getWidth() - 50;
        if (y + 50 > getHeight()) y = getHeight() - 50;

//        System.out.println("X:" + x + " Y:" + y);
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(140, 180, 249));
        setMaximumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
